# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-30 22:04
from __future__ import unicode_literals

from django.db import migrations, models
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20171028_1517'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test', markdownx.models.MarkdownxField()),
            ],
            options={
                'verbose_name': 'Markdown测试',
                'verbose_name_plural': 'Markdown测试',
            },
        ),
    ]
