# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-15 22:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relation', '0002_auto_20171015_2201'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departments',
            options={'verbose_name': '部门', 'verbose_name_plural': '部门'},
        ),
        migrations.AlterModelOptions(
            name='projects',
            options={'verbose_name': '项目', 'verbose_name_plural': '项目'},
        ),
        migrations.AlterModelOptions(
            name='staffs',
            options={'verbose_name': '员工', 'verbose_name_plural': '员工'},
        ),
    ]
